# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Reply(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, request_status: str='success', replay_id: int=-1, comment_id: int=None, object_type: str='normal', user_memo: str=None):  # noqa: E501
        """Reply - a model defined in Swagger

        :param request_status: The request_status of this Reply.  # noqa: E501
        :type request_status: str
        :param replay_id: The replay_id of this Reply.  # noqa: E501
        :type replay_id: int
        :param comment_id: The comment_id of this Reply.  # noqa: E501
        :type comment_id: int
        :param object_type: The object_type of this Reply.  # noqa: E501
        :type object_type: str
        :param user_memo: The user_memo of this Reply.  # noqa: E501
        :type user_memo: str
        """

        self.swagger_types = {
            'request_status': str,
            'replay_id': int,
            'comment_id': int,
            'object_type': str,
            'user_memo': str
        }

        self.attribute_map = {
            'request_status': 'request_status',
            'replay_id': 'replay_id',
            'comment_id': 'comment_id',
            'object_type': 'object_type',
            'user_memo': 'user_memo'
        }

        self._request_status = request_status
        self._replay_id = replay_id if replay_id != -1 else None
        self._comment_id = comment_id
        self._object_type = object_type
        self._user_memo = user_memo

    def to_dict(self):
        return {
            "request_status" : self.request_status,
            "comment_id" : self.comment_id,
            "object_type" : self.object_type,
            "replay_id" : self.replay_id,
            "user_memo" : self.user_memo
        }
    @classmethod
    def from_dict(cls, dikt) -> 'Reply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The reply of this Reply.  # noqa: E501
        :rtype: Reply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_status(self) -> str:
        """Gets the request_status of this Reply.


        :return: The request_status of this Reply.
        :rtype: str
        """
        return self._request_status

    @request_status.setter
    def request_status(self, request_status: str):
        """Sets the request_status of this Reply.


        :param request_status: The request_status of this Reply.
        :type request_status: str
        """
        allowed_values = ["success", "error", "warring"]  # noqa: E501
        if request_status not in allowed_values:
            raise ValueError(
                "Invalid value for `request_status` ({0}), must be one of {1}"
                .format(request_status, allowed_values)
            )

        self._request_status = request_status

    @property
    def replay_id(self) -> int:
        """Gets the replay_id of this Reply.


        :return: The replay_id of this Reply.
        :rtype: int
        """
        return self._replay_id

    @replay_id.setter
    def replay_id(self, replay_id: int):
        """Sets the replay_id of this Reply.


        :param replay_id: The replay_id of this Reply.
        :type replay_id: int
        """
        if replay_id is None:
            raise ValueError("Invalid value for `replay_id`, must not be `None`")  # noqa: E501

        self._replay_id = replay_id

    @property
    def comment_id(self) -> int:
        """Gets the comment_id of this Reply.


        :return: The comment_id of this Reply.
        :rtype: int
        """
        return self._comment_id

    @comment_id.setter
    def comment_id(self, comment_id: int):
        """Sets the comment_id of this Reply.


        :param comment_id: The comment_id of this Reply.
        :type comment_id: int
        """
        if comment_id is None:
            raise ValueError("Invalid value for `comment_id`, must not be `None`")  # noqa: E501

        self._comment_id = comment_id

    @property
    def object_type(self) -> str:
        """Gets the object_type of this Reply.


        :return: The object_type of this Reply.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this Reply.


        :param object_type: The object_type of this Reply.
        :type object_type: str
        """
        allowed_values = ["normal", "banned"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def user_memo(self) -> str:
        """Gets the user_memo of this Reply.


        :return: The user_memo of this Reply.
        :rtype: str
        """
        return self._user_memo

    @user_memo.setter
    def user_memo(self, user_memo: str):
        """Sets the user_memo of this Reply.


        :param user_memo: The user_memo of this Reply.
        :type user_memo: str
        """
        if user_memo is None:
            raise ValueError("Invalid value for `user_memo`, must not be `None`")  # noqa: E501

        self._user_memo = user_memo
